//performs addition of two numbers and three numbers Date : 11 Oct 2023 | 05:05 PM| Mohan Krishna S
public with sharing class Addition {
    //sum of two numbers  
    public static Integer sumOf2(Integer a, Integer b){
        return a+b;    
    }
    //sum of three numbers 
    public static Integer sumOf3(Integer a, Integer b, Integer c){
        return a+b+c;  
    }  
    //sum of four numbers 
    public static Integer sumOf4(Integer a, Integer b, Integer c, Integer d){
        return a+b+c+d;
    } 
    //sum of five numbers  
    public static Integer sumOf5(Integer a, Integer b, Integer c, Integer d, Integer e, Integer f){
        return a+b+c+d+e;
    }
}